### ISSUE TITLE
Final Setup usage

### ISSUE THREAD

**Issue by hdava** [oraclebase/dockerfiles#1]
Hello,

I have used your dockerfiles (which by the way are very nice) for testing a local Oracle 12cR2 + ORDS setup.

I have executed successfully (at least I think :)) the docker-compose and the two containers are running:

```
ordsservice_1  | 02-Jul-2018 19:04:23.546 WARNING [main] . *** jdbc.InitialLimit in configuration |apex|| is using a value of 3, this setting may not be sized adequately for a production environment ***
ordsservice_1  | 02-Jul-2018 19:04:23.601 INFO [main] . Creating Pool:|apex|al|
ordsservice_1  | 02-Jul-2018 19:04:23.601 INFO [main] . Configuration properties for: |apex|al|
ordsservice_1  | cache.caching=false
ordsservice_1  | cache.directory=/tmp/apex/cache
ordsservice_1  | cache.duration=days
ordsservice_1  | cache.expiration=7
ordsservice_1  | cache.maxEntries=500
ordsservice_1  | cache.monitorInterval=60
ordsservice_1  | cache.procedureNameList=
ordsservice_1  | cache.type=lru
ordsservice_1  | db.hostname=dbservice
ordsservice_1  | db.password=******
ordsservice_1  | db.port=1521
ordsservice_1  | db.servicename=pdb1
ordsservice_1  | db.username=APEX_LISTENER
ordsservice_1  | debug.debugger=false
ordsservice_1  | debug.printDebugToScreen=false
ordsservice_1  | error.keepErrorMessages=true
ordsservice_1  | error.maxEntries=50
ordsservice_1  | jdbc.DriverType=thin
ordsservice_1  | jdbc.InactivityTimeout=1800
ordsservice_1  | jdbc.InitialLimit=3
ordsservice_1  | jdbc.MaxConnectionReuseCount=1000
ordsservice_1  | jdbc.MaxLimit=10
ordsservice_1  | jdbc.MaxStatementsLimit=10
ordsservice_1  | jdbc.MinLimit=1
ordsservice_1  | jdbc.statementTimeout=900
ordsservice_1  | log.logging=false
ordsservice_1  | log.maxEntries=50
ordsservice_1  | misc.compress=
ordsservice_1  | misc.defaultPage=apex
ordsservice_1  | security.disableDefaultExclusionList=false
ordsservice_1  | security.maxEntries=2000
ordsservice_1  | security.requestValidationFunction=wwv_flow_epg_include_modules.authorize
ordsservice_1  | security.validationFunctionType=plsql
ordsservice_1  |
ordsservice_1  | 02-Jul-2018 19:04:23.602 WARNING [main] . *** jdbc.MaxLimit in configuration |apex|al| is using a value of 10, this setting may not be sized adequately for a production environment ***
ordsservice_1  | 02-Jul-2018 19:04:23.603 WARNING [main] . *** jdbc.InitialLimit in configuration |apex|al| is using a value of 3, this setting may not be sized adequately for a production environment ***
ordsservice_1  | 02-Jul-2018 19:04:23.941 INFO [main] . Oracle REST Data Services initialized
ordsservice_1  | Oracle REST Data Services version : 18.1.1.95.1251
ordsservice_1  | Oracle REST Data Services server info: Apache Tomcat/9.0.10
ordsservice_1  |
ordsservice_1  | 02-Jul-2018 19:04:23.973 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/u01/tomcat/webapps/ords.war] has finished in [7,326] ms
ordsservice_1  | 02-Jul-2018 19:04:23.975 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/u01/tomcat/webapps/i]
ordsservice_1  | 02-Jul-2018 19:04:24.084 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/u01/tomcat/webapps/i] has finished in [110] ms
ordsservice_1  | 02-Jul-2018 19:04:24.092 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
ordsservice_1  | 02-Jul-2018 19:04:24.215 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-jsse-nio-8443"]
ordsservice_1  | 02-Jul-2018 19:04:24.236 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
ordsservice_1  | 02-Jul-2018 19:04:24.250 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 7724 ms
```

However, now I was trying to execute a preconfigured ORDS api that I have done in Oracle XE 11g and I get the following error:

`  COMMIT; 
END;
Error report -
ORA-06550: linha 2, coluna 3:
PLS-00201: o identificador 'ORDS.ENABLE_SCHEMA' deve ser declarado
ORA-06550: linha 2, coluna 3:
PL/SQL: Statement ignored
ORA-06550: linha 9, coluna 3:
PLS-00201: o identificador 'ORDS.DEFINE_MODULE' deve ser declarado
ORA-06550: linha 9, coluna 3:
PL/SQL: Statement ignored
ORA-06550: linha 15, coluna 3:
PLS-00201: o identificador 'ORDS.DEFINE_TEMPLATE' deve ser declarado
ORA-06550: linha 15, coluna 3:
PL/SQL: Statement ignored
ORA-06550: linha 22, coluna 3:
PLS-00201: o identificador 'ORDS.DEFINE_HANDLER' deve ser declarado
ORA-06550: linha 22, coluna 3:
PL/SQL: Statement ignored
ORA-06550: linha 61, coluna 3:
PLS-00201: o identificador 'ORDS.DEFINE_PARAMETER' deve ser declarado
ORA-06550: linha 61, coluna 3:
PL/SQL: Statement ignored
ORA-06550: linha 71, coluna 3:
PLS-00201: o identificador 'ORDS.DEFINE_PARAMETER' deve ser declarado
ORA-06550: linha 71, coluna 3:
PL/SQL: Statement ignored
ORA-06550: linha 81, coluna 3:
PLS-00201: o identificador 'ORDS.DEFINE_PARAMETER' deve ser declarado
ORA-06550: linha 81, coluna 3:
PL/SQL: Statement ignored
ORA-06550: linha 91, coluna 3:
PLS-00201: o identificador 'ORDS.DEFINE_PARAMETER' deve ser declarado
ORA-06550: linha 91, coluna 3:
PL/SQL: Statement ignored
ORA-06550: linha 101, coluna 3:
PLS-00201: o identificador 'ORDS.DEFINE_PARAMETER' deve ser declarado
ORA-06550: linha 101, coluna 3:
PL/SQL: Statement ignored
ORA-06550: linha 111, coluna 3:
PLS-00201: o identificador 'ORDS.DEFINE_PARAMETER' deve ser declarado
ORA-06550: linha 111, coluna 3:
PL/SQL: Statement ignored
06550. 00000 -  "line %s, column %s:\n%s"
*Cause:    Usually a PL/SQL compilation error.
*Action:`

Can you please let me know what I'm missing or what I need to do?

Thank you

**Comment by oraclebase** [comment]
The errors would suggest ORDS is not installed properly.

My first suggestion would be to connect to the user you want to run the
service and run the ORDS.enable_schema command and see what happens.

Remember to do this you will need to be connected to the PDB.

Cheers

Tim...

**Comment by hdava** [comment]
Thank you! I managed to deploy my existing services. The issue was indeed not being connected to PDB. My experience with Oracle was using Oracle XE... can you please let me know what is the intended purpose of cbd1 vs pdb1? Thanks

**Comment by oraclebase** [comment]
The multitenant option is new in 12c. You can read about it here.

https://oracle-base.com/articles/12c/multitenant-overview-container-database-cdb-12cr1

Cheers

Tim...

**Comment by hdava** [comment]
Thank you for the info!
