### ISSUE TITLE
Question :  connection to the bbdd

### ISSUE THREAD

**Issue by angelcastroorange** [oraclebase/dockerfiles#11]
Using the default compose and not creating any persistent volume, everything starts up perfectly :-) . But to be able to connect to the bbdd through port 1521, either with any sql client, the existing data are the correct ones?
    environment:
      - SYS_PASSWORD=SysPassword1
      - PDB_PASSWORD=PdbPassword1
      - APEX_EMAIL=me@example.com
      - APEX_PASSWORD=ApexPassword1

I try to connect in all possible ways such as sys, sysdba, sysoper, etc... but I can not connect.
Sample : 

conn sys/SysPassword1@//IPHostBBDD:1521/pdb1
conn sysdba/SysPassword1@//IPHostBBDD:1521/pdb1

Error Message = ORA-28009: connection as SYS should be as SYSDBA or SYSOPER
Error Message = ORA-01017: invalid username/password; logon denied

**Comment by oraclebase** [comment]
When you connect to SYS you have to connect as SYSDBA.

conn sys/SysPassword1@//IPHostBBDD:1521/pdb1 as SYSDBA

Cheers

Tim...
