### ISSUE TITLE
ORA-01918: user 'APEX_PUBLIC_USER' does not exist

### ISSUE THREAD

**Issue by BlackWolfDEsign** [oraclebase/dockerfiles#14]
https://github.com/oraclebase/dockerfiles/blob/9f1de4749a941fa9306584da83e23ea78f37025e/database/ol7_19/scripts/start.sh#L175
https://github.com/oraclebase/dockerfiles/blob/9f1de4749a941fa9306584da83e23ea78f37025e/database/ol7_19/scripts/start.sh#L176

Hello I get two minor errors in these lines. I can only unlock the users with the **sqldeveloper** and the **password in quotes**. (sys as sysdba)

The message from the title comes from the script. 

thx for this dockerfiles,

**Comment by oraclebase** [comment]
That's odd. It works fine for me.

The only way APEX_PUBLIC_USER doesn't exist at that point is if APEX hasn't been installed. If APEX is installed, the user must exist.

Give me a few minutes. I'll do a clean build and check.

**Comment by oraclebase** [comment]
Just did a clean build. Both commands worked fine, and the users are open with the correct passwords.

**Comment by BlackWolfDEsign** [comment]
Yes, sorry for this misunderstanding. I think my password is being interpreted incorrectly. Yes the users exists despite the error message.
statement with sqldeveloper:
works: alter user ... by "MY_PW" _(with quotes)_
works not: alter user ... by MY_PW

maybe the problem is that my password starts with a number?

**Comment by oraclebase** [comment]
OK. So your password is freaking it out. I've changed the script to double-quote the passwords, so it should work for you now.

**Comment by BlackWolfDEsign** [comment]
wonderful dockerfiles :3
