### ISSUE TITLE
A strange performance issue, not sure how to debug

### ISSUE THREAD

**Issue by bayeslearnerold** [oraclebase/dockerfiles#16]
Hi, thanks for this wonderful little project.  I am able to successfully create my own docker images and services etc.  However, I am seeing a strange issue with performance. Basically, the system requires 1-2 "refresh" of the browser from time to time to correctly load the correct appearances (something with CSS or caching?).   

For example: 
![image](https://user-images.githubusercontent.com/68746303/108899784-d320c480-75e6-11eb-885e-145076e791d0.png)

becomes:
![image](https://user-images.githubusercontent.com/68746303/108899830-e2a00d80-75e6-11eb-9fb7-1968154e49db.png)

**Comment by bayeslearnerold** [comment]
It seemed to be related to my chrome browser or extension.  It works fine in firefox.  So thanks, you can close it.

**Comment by oraclebase** [comment]
As per user comment, it's a browser cache issue.
