### ISSUE TITLE
network access denied by access control list (ACL) ORA-06512

### ISSUE THREAD

**Issue by bayeslearnerold** [oraclebase/dockerfiles#17]
I created a new workspace with just one admin account and I'm running this tutorial and run into the following error: 

https://oracle.github.io/learning-library/developer-library/apex/remote-data-source/?page=README&lab=lab-2-populating-table#STEP1CreateaScript

network access denied by access control list (ACL) ORA-06512

ORA-29273: HTTP request failed ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 1157 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 757 ORA-24247: network access denied by access control list (ACL) ORA-06512: at "SYS.UTL_HTTP", line 380 ORA-06512: at "SYS.UTL_HTTP", line 1148 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 735 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 998 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 1413 ORA-06512: at "APEX_200200.WWV_FLOW_WEBSERVICES_API", line 655 ORA-06512: at line 1 ORA-06512: at "SYS.DBMS_SQL", line 1721

**Comment by oraclebase** [comment]
Hi.

This is not a problem with the build. It's the way Oracle works. The important bit is this.

ORA-24247: network access denied by access control list (ACL)

You need to create an ACL entry for anything you try to access remotely. Read this.

https://oracle-base.com/articles/12c/fine-grained-access-to-network-services-enhancements-12cr1

Cheers

Tim...

**Comment by bayeslearnerold** [comment]
I granted that to APEX_200200.  Now I have to deal with certificate and wallet.  This is fun.   Not really. :-(   I thought this tool is supposed to increase productivity.  I highly highly doubt end users have any clue with any of these.

**Comment by oraclebase** [comment]
These two sections show how to create the wallet.

https://oracle-base.com/articles/misc/azure-ad-authentication-for-oracle-apex-applications#wallet-setup

And configure it for APEX.

https://oracle-base.com/articles/misc/azure-ad-authentication-for-oracle-apex-applications#configure-apex-to-use-the-wallet

**Comment by bayeslearnerold** [comment]
Hi, I tried and the wallet seems to be working, but I'm still getting errors. I verified the 3 certs have been imported and   I verified the wallet is open during the API call because if I miss-spell the name or password, the error is different.  Any insights? 

> ORA-29273: HTTP request failed ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 1157 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 757 ORA-29024: Certificate validation failure ORA-06512: at "SYS.UTL_HTTP", line 380 ORA-06512: at "SYS.UTL_HTTP", line 1148 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 735 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 998 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 1413 ORA-06512: at "APEX_200200.WWV_FLOW_WEBSERVICES_API", line 655 ORA-06512: at line 1 ORA-06512: at "SYS.DBMS_SQL", line 1721


```
 insert into big_mac_index (country_name, country_iso, currency_code, local_price, dollar_exchange_rate, gdp_dollar, entry_date)
  select col001, col002, col003, col004, col005, col006, to_date(col007,'YYYY-MM-DD') 
  from table(
      apex_data_parser.parse( 
        p_content => apex_web_service.make_rest_request_b(
                p_url => 'https://raw.githubusercontent.com/TheEconomist/big-mac-data/master/source-data/big-mac-source-data.csv', 
                p_http_method => 'GET', 
                p_wallet_path => 'file:/u02/wallet/github',
                p_wallet_pwd => 'Welcome1!' ,
                p_https_host => 'www.github.com'), 
        
        p_file_name => 'big-mac-source-data.csv' , 
        p_skip_rows => 1 ) 
      );


```

**Comment by bayeslearnerold** [comment]
[oracle@529748fd0efc github]$ orapki wallet display -wallet .
Oracle PKI Tool Release 19.0.0.0.0 - Production
Version 19.3.0.0.0
Copyright (c) 2004, 2019, Oracle and/or its affiliates. All rights reserved.

Requested Certificates:
User Certificates:
Trusted Certificates:
Subject:        CN=www.github.com,O=GitHub\, Inc.,L=San Francisco,ST=California,C=US
Subject:        CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
Subject:        CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US

**Comment by oraclebase** [comment]
Typically, you should only load the root certificate, not the intermediate and domain certificates. Try recreating the wallet and only loading the root certificate.

If you are still getting the error then, it would suggest you are not configuring the wallet properly.

**Comment by bayeslearnerold** [comment]
Thanks!  It worked when I used another wallet with only root cert.   
However when I try to set up  wallet for the entire workspace, I saw another error.  LOL>  

> ORA-29273: HTTP request failed ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 1157 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 757 ORA-29248: an unrecognized WRL was used to open a wallet ORA-06512: at "SYS.UTL_HTTP", line 380 ORA-06512: at "SYS.UTL_HTTP", line 1148 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 735 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 998 ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 1413 ORA-06512: at "APEX_200200.WWV_FLOW_WEBSERVICES_API", line 655 ORA-06512: at line 5 ORA-06512: at "SYS.DBMS_SQL", line 1721

**Comment by oraclebase** [comment]
Did you use the path without the "file:" prefix?

Not this:

/path/to/wallet

This:

file:/path/to/wallet

**Comment by bayeslearnerold** [comment]
Thanks a bunch!  A lot of traps for sure.

**Comment by Karan28** [comment]
Hi @bayeslearner @oraclebase 

I am getting the same issue. I have asked my network/admin team to check if the certificates are imported are of root and not intermediate or domain certificate. 

Your help would be appreciated!

An error occurred while preparing and executing the package
Cause: java.sql.SQLException: ORA-20001: ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 1157
ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 757
ORA-06512: at "SYS.UTL_HTTP", line 380
ORA-06512: at "SYS.UTL_HTTP", line 1148
ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 735
ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 998
ORA-06512: at "APEX_200200.WWV_FLOW_WEB_SERVICES", line 1346
ORA-06512: at "APEX_200200.WWV_FLOW_WEBSERVICES_API", line 608
 error in procedure -29273-ORA-29273: HTTP request failed

**Comment by oraclebase** [comment]
This is not a problem with the build. This is a problem with your certificate setup in you wallet.

That process was explained above and I will relink here.

These two sections show how to create the wallet.

https://oracle-base.com/articles/misc/azure-ad-authentication-for-oracle-apex-applications#wallet-setup

And configure it for APEX.

https://oracle-base.com/articles/misc/azure-ad-authentication-for-oracle-apex-applications#configure-apex-to-use-the-wallet

Please don's use this as a generic forum. This is meant to be for comments about the build, not a general question/answer facility...
