### ISSUE TITLE
getting error during build

### ISSUE THREAD

**Issue by flik** [oraclebase/dockerfiles#2]
unzip:  cannot find or open linuxx64_12201_database.zip, linuxx64_12201_database.zip.zip or linuxx64_12201_database.zip.ZIP.
ERROR: Service 'dbservice' failed to build: The command '/bin/sh -c cd ${SOFTWARE_DIR}                                                      &&     unzip ${DB_SOFTWARE}                                                    &&     rm ${DB_SOFTWARE}' returned a non-zero code: 9

**Comment by oraclebase** [comment]
Hi.

You have to put the software in the correct location for it to work.

Cheers

Tim...
