### ISSUE TITLE
Error response from daemon: OCI runtime create failed: invalid mount

### ISSUE THREAD

**Issue by matefran** [oraclebase/dockerfiles#20]
Hi,
I use this image on multiple servers but on one I have this error: 

Error response from daemon: OCI runtime create failed: invalid mount {Destination:[/u01/config/instance1] Type:bind Source:/var/lib/docker/volumes/0c21146159500d3ad75113df9d1176c365345431ca116f784d67179a7a7ce73c/_data Options:[rbind]}: mount destination [/u01/config/instance1] not absolute: unknown

**Comment by oraclebase** [comment]
Hi.

My first question would be, are you mounting a persistent volume to CATALINA_BASE (/u01/config/instance1) location in the container? If you are, you need to make sure the permissions are set correctly on the physical directory.

Check out this article.

https://oracle-base.com/articles/linux/docker-host-file-system-permissions-for-container-persistent-host-volumes

Cheers

Tim...

**Comment by matefran** [comment]
hi, thanks for reply.  I have CATALINA_BASE="/u01/config/instance1" and the same dockerfile on lot of machines but ony two of them on the same network has this problem.

**Comment by oraclebase** [comment]
But is your CATALINA_BASE a persistent volume, or ephemeral inside the container?

For example, most of my containers at work keep the CATALINA_BASE on a persistent volume on the host file system. The containers are run using the following flag.

-v /path/to/host/volume:/u01/config/instance1

In this case, the host volume has to have the correct permissions for the container to be able to write to it.

**Comment by matefran** [comment]
Inside the container.

**Comment by matefran** [comment]
I checked now and every new install shows this error. Maybe something has changed in the last month?

**Comment by oraclebase** [comment]
You have checked you've got the correct software right?

I'm constantly updating the versions of Java, Tomcat, ORDS, APEX etc. You need to make sure you have the correct versions downloaded, or have reverted to old software versions in the Dockerfile.

I mostly use external volumes. I'll try a new build using the ephemeral storage. Give me a few minutes. :)

**Comment by oraclebase** [comment]
I've just some builds and I got OCI warnings, where I didn't a few days ago. I think maybe there is an update to oraclelinux:8-slim or podman. I Googled the error and there was a post saying we now need to add the  "--format docker" docker flag. I'm trying that now.

**Comment by matefran** [comment]
I will try.

PS.
I use ol7

**Comment by oraclebase** [comment]
It seems to be something with the permissions on the "/u01/config/instance1" mount point, but I can't tell what it is. I'm going to try a couple of things before bed, but I'm clutching at straws. Not really sure what it is, or why it has happened now. I tested this when the latest ORDS was released and it was fine. Not sure what's changed since. I am guessing it's the base oracle linux image, but I'm not sure.

**Comment by oraclebase** [comment]
I found one reference to this error saying to remove the VOLUME operation from the Dockerfile. That seems to have worked. So change this:

VOLUME [${CATALINA_BASE}]

To this:

#VOLUME [${CATALINA_BASE}]

Run the build and try again.

**Comment by oraclebase** [comment]
Just ran through a whole setup with the VOLUME operator removed. It worked fine for me. Give that a go and let me know how you get on. I'll have to do some more tests before I remove it from the build completely.

**Comment by matefran** [comment]
Yes, it's working for me too. Thank you very much for your help.

**Comment by oraclebase** [comment]
I've commented out the VOLUME operation on all the builds, as it's not really necessary.

It was giving issues on the current version of Docker, and a different, but equally annoying issue on the current version of Podman.

Thanks for the heads-up.
