### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed using Dockers for windows

### ISSUE THREAD

**Issue by Alao-Abiodun** [oraclebase/dockerfiles#21]
Hi, I am just learning Docker, and I have tried my best in searching for how to fix it
I am using windows to run my Docker.

This is it when I run the command: **docker run -d -p 3000:3000 -v ~/$(pwd):/src/app --name ireporter-app ireporter-app-image**

It ran and show me this output:
bd9df62788bcc68009b12180295df82282ef27b83e8cefbd7aded664a31320e4
docker: Error response from daemon: OCI runtime create failed: invalid mount {Destination:\Program Files\Git\src\app Type:bind Source:/run/desktop/mnt/host/c/Users/USER/c/Users/USER/OneDrive/Documents/PersonalProject/iReporter;C Options:[rbind rprivate]}: mount destination \Program Files\Git\src\app not absolute: unknown. 

Also, show me a pop up of a message saying: 
Docker Desktop has detected that you shared a Windows file into a WSL 2 container, which may perform poorly. Click here for more details.

When I run docker ps, I noticed my container is not running.

Any assistance I will be glad. Thanks

**Comment by oraclebase** [comment]
Hi.

1) I've never used Docker on Windows.
2) This is not a question about any of my docker builds, so why would I be able to comment?

Maybe you need to speak to the person who gave you the instructions for your build? 

Cheers

Tim...

**Comment by Alao-Abiodun** [comment]
Ok, Thanks
