### ISSUE TITLE
can not access in bash command

### ISSUE THREAD

**Issue by huy91-hub** [oraclebase/dockerfiles#24]
Hi Tim,
There is my issue below:
```
[root@localhost ol7_19]# docker run -dit --name ol7_19_con -p 1521:1521 -p 5500:5500 --shm-size="1G" -v /u01/volumes/ol7_19_con_u02/:/u02 ol7_19:latest
05fac7fb0af996ed7592b2aa0dcffdbef266cd1cfd88cb9f780e70436aa6b142
[root@localhost ol7_19]# docker ps -a
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS                            PORTS                                                                                  NAMES
05fac7fb0af9   ol7_19:latest   "/bin/sh -c 'exec ${…"   5 seconds ago   Up 4 seconds (health: starting)   0.0.0.0:1521->1521/tcp, :::1521->1521/tcp, 0.0.0.0:5500->5500/tcp, :::5500->5500/tcp   ol7_19_con
[root@localhost ol7_19]# docker exec -it ol7_19_con bash
Error response from daemon: Container 05fac7fb0af996ed7592b2aa0dcffdbef266cd1cfd88cb9f780e70436aa6b142 is not running
[root@localhost ol7_19]# docker ps -a
CONTAINER ID   IMAGE           COMMAND                  CREATED          STATUS                      PORTS     NAMES
05fac7fb0af9   ol7_19:latest   "/bin/sh -c 'exec ${…"   44 seconds ago   Exited (1) 35 seconds ago             ol7_19_con
[root@localhost ol7_19]#
```
Now I want to access in bash and run imdp command, but it shows me container is not running. I create docker image from your dockerfile.

**Comment by oraclebase** [comment]
Hi.

The "docker ps -a" output shows the container has been created for 5 seconds, which suggests this is a first time start. The database creation is done on the first time start, so it's going to take quite some time to create the database.

Rather than trying to connect at this point, you should use "docker logs --follow ol7_19_con" to tail the log file and wait for the database creation to complete. You can't do an import until you have a database. The log will give you some indication of what is happening during the creation.

The container will only remain up if it is working OK. If the start.sh file fails for any reason, the container will be stopped. It would seem to me there is a failure during the startup, which is why you can't connect. The "docker logs --follow ol7_19_con" command should include the information about the failures. You can then take corrective action and try again...

Cheers

Tim...

**Comment by huy91-hub** [comment]
When i run docker logs --follow ol7_19_con it shows below about the issue is related to that : **Proper permissions are not granted to create the directory or there is no space left in the volume.**
```
[root@localhost ol7_19]# docker logs --follow ol7_19_con
******************************************************************************
Handle shutdowns. Thu Jun 30 04:27:52 UTC 2022
docker stop --time=30 {container} Thu Jun 30 04:27:52 UTC 2022
******************************************************************************
******************************************************************************
Define fixConfig function. Thu Jun 30 04:27:52 UTC 2022
Fixes the config using the contents of the volume. Thu Jun 30 04:27:52 UTC 2022
Necessary when using persistent volume as rm and run will reset the config Thu Jun 30 04:27:52 UTC 2022
under the ORACLE_HOME. Thu Jun 30 04:27:52 UTC 2022
******************************************************************************
******************************************************************************
Create networking files if they don't already exist. Thu Jun 30 04:27:52 UTC 2022
******************************************************************************
******************************************************************************
First start, so create networking files. Thu Jun 30 04:27:52 UTC 2022
******************************************************************************
******************************************************************************
Check if database already exists. Thu Jun 30 04:27:52 UTC 2022
******************************************************************************

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 30-JUN-2022 04:27:52

Copyright (c) 1991, 2019, Oracle.  All rights reserved.

Starting /u01/app/oracle/product/19.0.0/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
System parameter file is /u01/app/oracle/product/19.0.0/dbhome_1/network/admin/listener.ora
Log messages written to /u01/app/oracle/diag/tnslsnr/05fac7fb0af9/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                30-JUN-2022 04:27:52
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /u01/app/oracle/product/19.0.0/dbhome_1/network/admin/listener.ora
Listener Log File         /u01/app/oracle/diag/tnslsnr/05fac7fb0af9/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[FATAL] [DBT-06006] Unable to create directory: (/u02/oradata/cdb1/).
   CAUSE: Proper permissions are not granted to create the directory or there is no space left in the volume.
******************************************************************************
Set the PDB to auto-start. Thu Jun 30 04:27:57 UTC 2022
******************************************************************************

SQL*Plus: Release 19.0.0.0.0 - Production on Thu Jun 30 04:27:57 2022
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> alter system set db_create_file_dest='/u02/oradata'
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> alter pluggable database pdb1 save state
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> alter system set local_listener='LISTENER'
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> Disconnected
******************************************************************************
Store config files in case persistent volume is used. Thu Jun 30 04:27:58 UTC 2022
******************************************************************************
mkdir: cannot create directory '/u02/config': Permission denied
cp: cannot create regular file '/u02/config/': Not a directory
******************************************************************************
Flip the auto-start flag. Thu Jun 30 04:27:59 UTC 2022
******************************************************************************
sed: can't read /u02/config/oratab: No such file or directory
cp: cannot stat '/u02/config/oratab': No such file or directory
mv: cannot stat '/u01/app/oracle/product/19.0.0/dbhome_1/dbs/orapwcdb1': No such file or directory
mv: cannot stat '/u01/app/oracle/product/19.0.0/dbhome_1/dbs/spfilecdb1.ora': No such file or directory
mv: cannot stat '/u01/app/oracle/admin': No such file or directory
mv: cannot move '/u01/app/oracle/fast_recovery_area' to '/u02/config/cdb1': No such file or directory
mv: cannot move '/u01/app/oracle/diag' to '/u02/config/cdb1': No such file or directory
cp: cannot stat '/u02/config/oratab': No such file or directory
******************************************************************************
Install APEX. Thu Jun 30 04:27:59 UTC 2022
******************************************************************************

SQL*Plus: Release 19.0.0.0.0 - Production on Thu Jun 30 04:27:59 2022
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> alter session set container = pdb1
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> create tablespace apex datafile size 1m autoextend on next 1m
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> ...set_appun.sql
declare
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


Disconnected
******************************************************************************
Tail the alert log file as a background process Thu Jun 30 04:28:00 UTC 2022
and wait on the process so script never ends. Thu Jun 30 04:28:00 UTC 2022
******************************************************************************
tail: cannot open '/u01/app/oracle/diag/rdbms/cdb1/cdb1/trace/alert_cdb1.log' for reading: No such file or directory
tail: no files remaining

```

And when I run docker ps -a you can see the port does not setup.
```
[root@localhost ol7_19]# docker ps -a
CONTAINER ID   IMAGE           COMMAND                  CREATED       STATUS                   PORTS     NAMES
05fac7fb0af9   ol7_19:latest   "/bin/sh -c 'exec ${…"   2 hours ago   Exited (1) 2 hours ago             ol7_19_con
[root@localhost ol7_19]#
```

**Comment by huy91-hub** [comment]
so when I run docker with mounting host machine to have much capacity, it has a port but it shows **Only (2,910MB) free space is available on the location (/u02/oradata/cdb1/).**

**[root@localhost ol7_19]# docker run -dit --name ol7_19_con -p 1521:1521 -p 5500:5500 --shm-size="1G" -v /home/huynn/Downloads/share:/var/lib/sharedata  ol7_19:latest
296c0dd12a35abe22cead81118fb621dbad08cedae05d553a5405a96b229077e
[root@localhost ol7_19]# docker ps -a
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS                            PORTS                                                                                  NAMES
296c0dd12a35   ol7_19:latest   "/bin/sh -c 'exec ${…"   7 seconds ago   Up 7 seconds (health: starting)   0.0.0.0:1521->1521/tcp, :::1521->1521/tcp, 0.0.0.0:5500->5500/tcp, :::5500->5500/tcp   ol7_19_con
[root@localhost ol7_19]# docker logs ol7_19_con
******************************************************************************
Handle shutdowns. Thu Jun 30 06:45:12 UTC 2022
docker stop --time=30 {container} Thu Jun 30 06:45:12 UTC 2022
******************************************************************************
******************************************************************************
Define fixConfig function. Thu Jun 30 06:45:12 UTC 2022
Fixes the config using the contents of the volume. Thu Jun 30 06:45:12 UTC 2022
Necessary when using persistent volume as rm and run will reset the config Thu Jun 30 06:45:12 UTC 2022
under the ORACLE_HOME. Thu Jun 30 06:45:12 UTC 2022
******************************************************************************
******************************************************************************
Create networking files if they don't already exist. Thu Jun 30 06:45:12 UTC 2022
******************************************************************************
******************************************************************************
First start, so create networking files. Thu Jun 30 06:45:12 UTC 2022
******************************************************************************
******************************************************************************
Check if database already exists. Thu Jun 30 06:45:12 UTC 2022
******************************************************************************

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 30-JUN-2022 06:45:12

Copyright (c) 1991, 2019, Oracle.  All rights reserved.

Starting /u01/app/oracle/product/19.0.0/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
System parameter file is /u01/app/oracle/product/19.0.0/dbhome_1/network/admin/listener.ora
Log messages written to /u01/app/oracle/diag/tnslsnr/296c0dd12a35/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                30-JUN-2022 06:45:13
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /u01/app/oracle/product/19.0.0/dbhome_1/network/admin/listener.ora
Listener Log File         /u01/app/oracle/diag/tnslsnr/296c0dd12a35/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[FATAL] [DBT-06604] The location specified for 'Data Files Location' has insufficient free space.
   CAUSE: Only (2,910MB) free space is available on the location (/u02/oradata/cdb1/).
   ACTION: Choose a 'Data Files Location' that has enough space (minimum of (3,794MB)) or free up space on the specified location.
******************************************************************************
Set the PDB to auto-start. Thu Jun 30 06:45:18 UTC 2022
******************************************************************************

SQL*Plus: Release 19.0.0.0.0 - Production on Thu Jun 30 06:45:18 2022
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> alter system set db_create_file_dest='/u02/oradata'
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0**

**Comment by oraclebase** [comment]
OK. So this is the error.

[FATAL] [DBT-06006] Unable to create directory: (/u02/oradata/cdb1/).
   CAUSE: Proper permissions are not granted to create the directory or there is no space left in the volume.

You need to use an external volume for the data files, and make sure they have the correct permissions. You probably need to read this.

https://oracle-base.com/articles/linux/docker-host-file-system-permissions-for-container-persistent-host-volumes#host-setup

For example, if the persistent volume on your host is this.

/u01/volumes/ol7_19_con_u02

You would do this.

groupadd -g 1042 docker_fg
chown -R :docker_fg /u01/volumes
chmod -R 775 /u01/volumes
chmod -R g+s /u01/volumes
usermod -aG docker_fg docker_user

When you run the container, you would include the volume.

 -v /u01/volumes/ol7_19_con_u02/:/u02

You now have the ownership and permissions inside the container matching those outside the container.

Cheers

Tim...

**Comment by huy91-hub** [comment]
I don't understand where I add those code:
```
groupadd -g 1042 docker_fg
chown -R :docker_fg /u01/volumes
chmod -R 775 /u01/volumes
chmod -R g+s /u01/volumes
usermod -aG docker_fg docker_user
```

I add in your docker file but it returned a non-zero code: 1.

**Comment by oraclebase** [comment]
This is done on the host server, not in the Docker config.

The point is the persistent volume on the host server (which holds the data files) needs to be read/write from within the Docker container. To make sure this can happen, you need to make sure the permissions on the host volume are correct, so when the container starts it can access the persistent storage.

This is why I mention "host" in the comment and in the article. Host is the server you are running containers on.

**Comment by huy91-hub** [comment]
Thank u Tim. I  ran bash command with your instructions. But can I configure my dockerfile base on your dockerfile such as run volume outside container as above or add imdp command on your dockerfile?

**Comment by oraclebase** [comment]
Persistent Volumes:
The Dockerfile by definition has no idea where the persistent volumes are coming from. You could build the image and share it with people, without knowing where their persistent storage is. This is the way Docker works. So you will always have to map the persistent volume on your host to the /u02 location. Configuration of the host has to be done by you in advance of starting a container.

Import:
Remember, the Dockerfile commands are run at build time, not at runtime, so you can't put an import into it as there is no database present at build time.

If you wanted to you could add stuff to the start.sh script, as that is run at runtime. You would need to add your commands after the database is created, but before the final tail comment.

I would suggest you create a script to do what you want, and call it from the start.sh script.

**Comment by huy91-hub** [comment]
I try to create a way you suggest.  I am appreciate with your guide. Can you give me contact of you for the future?

**Comment by sahaniarun** [comment]
Dear all, will you update, if the oracle container can be used for the
production deployment. Will it support heavy traffic workload.

Arun

**Comment by oraclebase** [comment]
This build is something I've done for fun, and to help people understand how Docker works. I would not use it for production.

In general terms Docker can be used for production. Oracle support it. I personally wouldn't use Docker for a production database, but some people might.

In terms of performance, Docker is capable for running a heavy workload, providing the host machine the container is running on has a lot of resources (CPU and RAM) and you size your memory structures accordingly. It would also need the persistent storage to be placed on some high performance storage.

Docker is no different to any other system. If you run it on small hardware with limited resources, it's not going to cope with high workloads.
