### ISSUE TITLE
ords/ol8_ords/scripts/start.sh has issue

### ISSUE THREAD

**Issue by Samraw003** [oraclebase/dockerfiles#26]
Hi,

Thanks a ton for wonderful scripts!! There is an issue in the mentioned script:

function check_db {
  CONNECTION=$1
  RETVAL=`/u01/sqlcl/bin/sql -silent ${CONNECTION} <<EOF
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF TAB OFF
SELECT 'Alive' FROM dual;
EXIT;
EOF`

ISSUE: if condition is reversed!! 
 if [ "${RETVAL}" = "Alive" ]; then
    DB_OK=0
  else
    DB_OK=1
  fi
}

**Comment by oraclebase** [comment]
Have you looked at how that variable is used?

while [ ${DB_OK} -eq 1 ]
do
  echo "DB not available yet. Waiting for 30 seconds."
  sleep 30
  check_db ${CONNECTION}
done

So the code works. You might not like they way the 1 and 0 are used, but they are consistent.

When I wrote it I was thinking of exit codes , where 0 means success, and 1 is a generic error.

Cheers

Tim...
