### ISSUE TITLE
Traps do not work

### ISSUE THREAD

**Issue by chfloreck** [oraclebase/dockerfiles#7]
First - Your youtube Video is realy great.
However, I run into an problem.

If I stop the docker container, the traps inside the run script do not work.
I think, this is because the run script is a "subshell" and therefore does not receive the signals?

THX
Christian

**Comment by oraclebase** [comment]
Question: Are you doing the shutdown with the timeout option? The default timeout is 10 seconds, which is really quick, so a longer timeout would be necessary for a clean shutdown.

**Comment by chfloreck** [comment]
ps -e looks like this:
=============

oracle       1     0  0 18:08 pts/0    00:00:00 /tini -- /home/oracle/scripts/db_try.sh
oracle       6     1  0 18:08 pts/0    00:00:00 /bin/sh /home/oracle/scripts/db_try.sh

/bin/sh /home/oracle/scripts/db_try.sh:
=========================
ORACLE_SID=mydb
ORAENV_ASK=NO
. oraenv
function gracefulshutdown {
  dbshut $ORACLE_HOME
}

trap gracefulshutdown SIGINT
trap gracefulshutdown SIGTERM
trap gracefulshutdown SIGKILL

lsnrctl start

sqlplus / as sysdba << EOF
startup;
exit;
EOF
tail -f ${ORACLE_BASE}/diag/rdbms/${ORACLE_SID}/${ORACLE_SID}/trace/alert_${ORACLE_SID}.log



I use default, 10 sceonds:  "docker stop devXE"
I'll check timeout  option 
Hower, the alertlog shows no "shutdown":

[oracle@devXE trace]$ tail -f alert_mydb.log
===========================================================
Dumping current patch information
===========================================================
No patches have been applied
===========================================================
2019-10-04T17:44:41.484779+00:00
db_recovery_file_dest_size of 7206 MB is 4.85% used. This is a
user-specified limit on the amount of space that will be used by this
database for recovery-related files, and does not reflect the amount of
space available in the underlying filesystem or ASM diskgroup.

**Comment by chfloreck** [comment]
> 
> 
> Question: Are you doing the shutdown with the timeout option? The default timeout is 10 seconds, which is really quick, so a longer timeout would be necessary for a clean shutdown.

Well I increased to 10 Seconds - it did not help.
I guess that's because it did not have processid 1.
I installed tini.

oracle 1 0 0 18:08 pts/0 00:00:00 /tini -- /home/oracle/scripts/db_try.sh
oracle 6 1 0 18:08 pts/0 00:00:00 /bin/sh /home/oracle/scripts/db_try.sh

That does not  help....

**Comment by oraclebase** [comment]
Hi.

I've not had chance to check it myself. You say you've increased it to 10 seconds, but 10 seconds is the default, so that is not an increase. :) I would expect at least a couple of minutes...

Cheers

Tim...

**Comment by chfloreck** [comment]
Hi Tim,

I set timeout to 600 - it didn't help

Christian

**Comment by oraclebase** [comment]
Hi.

I just did this.

docker stop ol7_19_ords_db_1 -t 300

The alert log immediately showed this.

2019-10-05T21:07:51.917403+00:00
Shutting down ORACLE instance (immediate) (OS id: 3615)
2019-10-05T21:07:54.487370+00:00
Stopping background process SMCO
2019-10-05T21:07:55.510148+00:00
Shutting down instance: further logons disabled

etc.

Stopping background process VKTM
2019-10-05T21:08:18.156822+00:00
Instance shutdown complete (OS id: 3615)

It responded instantly to signal and completed the entire shutdown before the timeout completed.

It looks like it's working as planned to me!

Cheers

Tim...

**Comment by oraclebase** [comment]
BTW: The time is out by 1 hour on this VM, hence the 21:08 instead of 22:08... :)

**Comment by chfloreck** [comment]
Hi Tim,

thanks a lot.
Manual-not-read-error, I must admit. :-(
I did some changes in the "start" script - which caused this error.
Now it runs fne.

Again:
Thanks for your Youtube channel and the dockers.

Have a nice weekend
Christian



Am Sa., 5. Okt. 2019 um 23:11 Uhr schrieb Tim Hall <notifications@github.com

**Comment by oraclebase** [comment]
No problem. I'm glad i's sorted.

I would always suggest doing the build "as is" at first. Once you prove to yourself it all works, then you can try changing things. :)

Cheers

Tim...
