### ISSUE TITLE
same error in several compose versions : ORA-12547:

### ISSUE THREAD

**Issue by angelcastroorange** [oraclebase/dockerfiles#9]
I tried several versions of the compose directory and all of them got the same error:
db_1         | SQL*Plus: Release 19.0.0.0.0 - Production on Sun Jul 5 23:59:22 2020
db_1         | Version 19.3.0.0.0
db_1         |
db_1         | Copyright (c) 1982, 2019, Oracle.  All rights reserved.
db_1         |
db_1         | ERROR:
db_1         | ORA-12547: TNS:lost contact
db_1         |
db_1         |
db_1         | Enter user-name: SP2-0306: Invalid option.
db_1         | Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
db_1         | where <logon> ::= <username>[/<password>][@<connect_identifier>]
db_1         |       <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
db_1         | Enter user-name: SP2-0306: Invalid option.
db_1         | Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
db_1         | where <logon> ::= <username>[/<password>][@<connect_identifier>]
db_1         |       <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
db_1         | SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus
db_1         | ******************************************************************************
db_1         | Tail the alert log file as a background process Sun Jul 5 23:59:22 UTC 2020
db_1         | and wait on the process so script never ends. Sun Jul 5 23:59:22 UTC 2020
db_1         | ******************************************************************************
db_1         | tail: cannot open '/u01/app/oracle/diag/rdbms/cdb1/cdb1/trace/alert_cdb1.log' for reading: Too many levels of symbolic links
db_1         | tail: no files remaining
ords_1       | DB not available yet. Waiting for 30 seconds.

**Comment by oraclebase** [comment]
Looks like there is no database to connect to. When you did the docker-compose up, did you see the database creation happen?

**Comment by angelcastroorange** [comment]
**Upsss, he's right :-(  I assumed the bbdd was lifting correctly.  But it doesn't.**


[FATAL] [DBT-05509] Failed to connect to the specified database (cdb1).
   CAUSE: OS Authentication might be disabled for this database (cdb1).
   ACTION: Specify a valid sysdba user name and password to connect to the database.
******************************************************************************
Set the PDB to auto-start. Mon Jul 6 10:12:06 UTC 2020
******************************************************************************

SQL*Plus: Release 19.0.0.0.0 - Production on Mon Jul 6 10:12:06 2020
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

ERROR:
ORA-12547: TNS:lost contact


Enter user-name: SP2-0306: Invalid option.
Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
Enter user-name: SP2-0306: Invalid option.
Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus
******************************************************************************
Store config files in case persistent volume is used. Mon Jul 6 10:12:06 UTC 2020
******************************************************************************
******************************************************************************
Flip the auto-start flag. Mon Jul 6 10:12:06 UTC 2020
******************************************************************************
mv: cannot stat '/u01/app/oracle/product/19.0.0/dbhome_1/dbs/orapwcdb1': No such file or directory
mv: cannot stat '/u01/app/oracle/product/19.0.0/dbhome_1/dbs/spfilecdb1.ora': No such file or directory
mv: cannot stat '/u01/app/oracle/admin': No such file or directory
mv: inter-device move failed: '/u01/app/oracle/diag' to '/u02/config/cdb1/diag'; unable to remove target: Directory not empty


**And if I launch it with root permissions 👎** 

ERROR:
ORA-12547: TNS:lost contact


Enter user-name: SP2-0306: Invalid option.
Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
Enter user-name: SP2-0306: Invalid option.
Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus
******************************************************************************
Store config files in case persistent volume is used. Mon Jul 6 10:23:08 UTC 2020
******************************************************************************
******************************************************************************
Flip the auto-start flag. Mon Jul 6 10:23:08 UTC 2020
******************************************************************************
mv: '/u01/app/oracle/fast_recovery_area' and '/u02/config/cdb1/fast_recovery_area' are the same file
mv: '/u01/app/oracle/diag' and '/u02/config/cdb1/diag' are the same file
******************************************************************************
Install APEX. Mon Jul 6 10:23:08 UTC 2020
******************************************************************************

**Comment by oraclebase** [comment]
I've just done the following:

- Built a new VM using Oracle Linux 7 and Docker.
- Build the 19c and ORDS images.
- Run the compose using this.

https://github.com/oraclebase/dockerfiles/tree/master/compose/ol7_19_ords

You have two options:

1) You comment out the external volumes from the compose file for the database and ORDS containers.

or

2) You use volumes that have the correct permissions set. The build expects external volumes to be build expect the external volume to be owned by a group with a group ID of 1042. For example, this is what I use to prepare the external volumes on my host machine.

mkdir -p /u01/volumes/ol7_19_ords_tomcat
mkdir -p /u01/volumes/ol7_19_ords_db

# As root user.
groupadd -g 1042 docker_fg
chown -R :docker_fg /u01
chmod -R 775 /u01/volumes
chmod -R g+s /u01/volumes
usermod -aG docker_fg docker_user

Either way, the build works fine for me in both those scenarios.

I wrote about the file permissions here.

https://oracle-base.com/articles/linux/docker-host-file-system-permissions-for-container-persistent-host-volumes

**Comment by oraclebase** [comment]
FYI: I've added a note about this to the README.md of the containers.

**Comment by angelcastroorange** [comment]
Thank you very much, Tim. :-)

I tried option 2 but it still gives me problems, I guess after so many days with this I'm exhausted and not very thin. 
Try option 1 : comment out the external volumes from the compose file for the database and ORDS containers. And I compile everything perfectly without errors.

The web applications deployments are done but I can't get into any of the apex urls, either 
http://host:port/apex or http://host:port/apex/apex_admin giving both an http 404.  :-(

**Comment by oraclebase** [comment]
Your URLs are incorrect. Try this.

http://host:port/ords/

**Comment by angelcastroorange** [comment]
YESSSSSSSSSSSSSSSSSSSSSSSS !!! Thank you very much! :-)
